name: Code quality checks

on:
    push:
        branches:
            - master
    pull_request:
        branches:
            - master

env:
  UV_VERSION: 0.8.17

jobs:
    setup:
        runs-on: ubuntu-24.04
        steps:
            - uses: actions/checkout@v4

            - name: Install uv
              uses: astral-sh/setup-uv@v6.7.0
              with:
                version: "${{ env.UV_VERSION }}"
                enable-cache: true
                cache-dependency-glob: uv.lock

            - name: Set up Python
              uses: actions/setup-python@v6.0.0
              with:
                python-version-file: pyproject.toml

            - name: Install dependencies
              run: |-
                uv sync --all-extras --all-groups --locked

    lint:
        runs-on: ubuntu-24.04
        needs:
            - setup
        steps:
            - name: Run linting with Ruff
              run: uv run ruff check --output-format=github

            - name: Run code formatting with Ruff
              if: ${{ !cancelled() }}
              run: uv run ruff format --check

            - name: Run type checking
              if: ${{ !cancelled() }}
              run: uv run basedpyright

    tests:
        runs-on: ubuntu-24.04
        needs:
            - setup
        steps:
            - name: Run tests
              run: uv run pytest
